// <auto-generated />
namespace Project_Unite.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class jonny_please : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(jonny_please));
        
        string IMigrationMetadata.Id
        {
            get { return "201703161844454_jonny_please"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
